/* Copyright (c) 2026 hors<horsicq@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include "xemulunpacker_eronana.h"

XEmulUnpackerEronana::XEmulUnpackerEronana(QObject *pParent) : XEmulUnpacker(pParent)
{
}

QString XEmulUnpackerEronana::getPackerName() const
{
    return QStringLiteral("Eronana Packer");
}

XEmulUnpacker::OPTIONS XEmulUnpackerEronana::getDefaultOptions() const
{
    OPTIONS options;
    // Eronana Packer utilizes data compression to reduce the PE size.
    // A limit of 15,000,000 steps provides ample cycles for the emulator 
    // to complete the decompression loop and rebuild the IAT seamlessly.
    options.nMaxSteps = 15000000; 
    return options;
}

bool XEmulUnpackerEronana::matchOEP(const OEP_CONTEXT &c, const OPTIONS &options) const
{
    Q_UNUSED(options)
    
    // As per the repository, Eronana Packer is exclusively built for Win32.
    // It has no capability to pack or execute 64-bit binaries.
    if (c.bIs64) {
        return false;
    }

    // Like most basic 32-bit packers, the decompression stub must balance 
    // the stack (cleaning up local variables or using POPAD) before transitioning 
    // execution back to the Original Entry Point.
    if (c.nSpDelta != 0) {
        return false;
    }

    // Match typical Win32 tail-jump signatures used by PE compressors to jump to the OEP.

    // Pattern 1: Direct relative 5-byte jump (JMP offset)
    // Opcode: E9 XX XX XX XX
    if ((c.nPrevSize == 5) && (c.prev8() == 0xE9)) {
        return true;
    }

    // Pattern 2: Push OEP address onto the stack and return (PUSH imm32 -> RET)
    // Opcodes: 68 XX XX XX XX followed by C3
    if ((c.nPrevSize == 1) && (c.prev8() == 0xC3)) {
        if (c.matchSignature(c.nPrevAddress - 5, "68........")) {
            return true;
        }
    }

    // Pattern 3: Indirect absolute jump via register (e.g., JMP EAX, JMP ECX)
    // Opcodes: FF E0 through FF E7
    if ((c.nPrevSize == 2) && (c.prev16() >= 0xE0FF && c.prev16() <= 0xE7FF)) {
        return true;
    }

    // Pattern 4: Indirect jump via memory pointer (JMP DWORD PTR [mem])
    // Opcode: FF 25 XX XX XX XX -> Little Endian for the first two bytes is 0x25FF
    // This is often generated by C++ compilers for function pointer execution.
    if ((c.nPrevSize == 6) && (c.prev16() == 0x25FF)) {
        return true;
    }

    return false;
}